# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-05 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=25)),
                ('last_Name', models.CharField(max_length=25)),
                ('DateOfBirth', models.DateField()),
                ('gender', models.BooleanField()),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('userName', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
