# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-06 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sulekhaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='DateOfBirth',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='first_Name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_Name',
        ),
    ]
